[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "digital_writing"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.0,<3.14"
pandas = ">=2.2.3,<3"
jupyterlab = ">=4.3.0,<5"
openpyxl = ">=3.1.5,<4"
matplotlib = ">=3.9.2,<4"
wordcloud = ">=1.9.4,<2"
spacy = ">=3.7.6,<4"
pip = ">=24.3.1,<25"

[pypi-dependencies]
spacytextblob = ">=5.0.0,<6"
