name: deploy-jupyterlite

on:
  push:
    branches:
      - "main"
  # Just to check that we don't have a regression in pull-requests
  pull_request:
    branches:
      - '*'

jobs:
  deploy-jupyterlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements-jupyterlite.txt

      - name: Build JupyterLite
        run: make build-jupyterlite

    # Until we have a public repository, we cannot deploy on GitHub Pages.
    #   - name: Update the main gh-page website
    #     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #     uses: peaceiris/actions-gh-pages@v4
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./jupyterlite/dist
    #       commit_message: "[ci skip] ${{ github.event.head_commit.message }}"